language: go

sudo: required

dist: trusty

go:
  - 1.6.3
  - 1.7
  - tip

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test';"
  - psql -c "CREATE DATABASE test;"

install: go get github.com/constabulary/gb/...

script: gb test -v
